version: "2"
services:
  php:
    build: './docker-config/php/'
    networks:
      - backend
    volumes:
      - .:/var/www/html/
  apache:
    build: './docker-config/apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=1234
networks:
  frontend:
  backend:


