version: "2"
services:
  php-apache:
    build: 'docker-config/php-apache/'
    volumes:
      - .:/var/www/html/
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8082:80"
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234   
networks:
  frontend:
  backend: